### ISSUE TITLE
Why are you not even mentioning me?

### ISSUE THREAD

**Issue by Tomato6966** [navaneethkm004/distube-music-bot#3]
LMFAO

**Comment by navaneethkm004** [comment]
Bro. Look in your license. Every contributor can put the copy of the bot without mentioning the owner. I contributed your project. So i can put without mentioning you.

**Comment by navaneethkm004** [comment]
https://github.com/Tomato6966/Music-Bot-with-Filter/blob/main/LICENSE#L487

https://github.com/Tomato6966/distube-music-bot/blob/main/LICENSE#L475
